# 40k steps, 3h to almost optimal, but still inconsistent
name: "Hopper"

# Environment configuration
env:
  num: 4
  group: "Gymnasium"
  name: "Hopper-v5"
  actions:
    - type: "Discretized_Continuous"
      bins: 9
      num: 3

# Replay ratio
replay:
  ratio: 0.5

# Model configuration
model:
  embedding:
    - type: "MLP"
      segments:
        - range: [0, 11]
