# MuJoCo Humanoid
name: "RLGym"

# Environment configuration
env:
  num: 1
  group: "RLGym"
  name: "Soccar"
  actions:
    - type: "Discrete"
      num_options: 90

# Evaluation configuration
eval:
  frequency: 0  # Rendering is only available externally

# Ratio configuration
replay:
  ratio: 0.25

# Model configuration
model:

  embedding:
    # All MLP (RLGym_2026-04-26_07-06-10)
    # - type: "MLP"
    #   segments:
    #   - range: [0, 132]  # All observations for 2v2

    # All Attention
    - type: "Attention"
      segments:
        - range: [0, 9]  # Ball observations
        # TODO: Add locations to 34 pads and split by segment of 4 (timer, x, y, z)
        - range: [9, 42]  # 34 pads
        - range: [42, 72]  # Self car state plus observations
        - range: [72, null]  # Other car observations
          segment_len: 20
          max_segments: 5

    # Attention (ball + cars) + MLP (pads + car input)
    # - type: "Attention"
    #   segments:
    #     - range: [0, 9]  # Ball observations
    #     # - range: [43, 72]  # Self car observations + input observations
    #     - range: [52, 72]  # Self car observations
    #     - range: [72, null]  # Other car observations, `null` indicates to go until the end of the observation
    #       segment_len: 20  # The range from 72 to the end is split into segments of length 20 for attention processing
    #       max_segments: 5  # Max number of possible segments to generate from the decoder
    # - type: "MLP"
    #   segments:
    #     # - range: [9, 42]  # 34 pads
    #     - range: [9, 52]  # 34 pads, then 9 car input observations

    # CNN Example
    # - type: "CNN"
    #   segments:
    #     offset: 25  # Starting index of the image observations
    #     image_dim: [1, 3, 3]  # Reshape to CxHxW
